### ISSUE TITLE
CircleCI for PRs

### ISSUE THREAD

**Issue by julianneswinoga** [julianneswinoga/flightgear-python#10]
As shown in #9 CircleCI did not trigger a build. For easier community contributions this is required.

**Comment by juhannc** [comment]
Is there any particular reason why you want to use CircleCI? I find that GitHub Action integrates nicer with GitHub (kinda obviously) and with all the [existing templates](https://github.com/actions) it's easy to use

**Comment by julianneswinoga** [comment]
I've [used](https://github.com/OpenAstroTech/OpenAstroTracker-Firmware/tree/develop/.github/workflows) [both](https://github.com/OpenAstroTech/OATFWGUI/tree/master/.github) and they're both terrible :laughing: 
CircleCI has faster runners in the free tier, as well as the ability to easily rerun jobs with `ssh` for debugging. CircleCI also has templates (they call them [orbs](https://circleci.com/orbs/)) but I don't think they're as mature or maintained. IMO for me it's a bit of a tossup on which I go with (and probably depends on which one has annoyed me most recently :rofl: )

**Comment by juhannc** [comment]
Interesting, did know CircleCI was faster. I'm used to GitLab CI due to work and am still in awe of the speed of GitHub Actions. And also how easy it is to define multiple workflow files
