### ISSUE TITLE
Examples giving errors

### ISSUE THREAD

**Issue by dershow** [julianneswinoga/flightgear-python#8]
Thank you for this project.  Seems very interesting.  

I'm trying out the examples.   Simple_fdm.py seems to work as expected.  

However, if I run simple_gui.py I receive an error:

`line 2728, in _parse
    raise ConstError(f"parsing expected {repr(self.value)} but parsed {repr(obj)}", path=path)
construct.core.ConstError: Error in path (parsing) -> version
parsing expected 8 but parsed 402653184
`

And if I run simple_ctrls.py I get an error:
` line 2728, in _parse
    raise ConstError(f"parsing expected {repr(self.value)} but parsed {repr(obj)}", path=path)
construct.core.ConstError: Error in path (parsing) -> version
parsing expected 27 but parsed 24`

These errors don't really explain what is wrong, or what to do about it.  
Any additional guidance would be appreciated.  

Thanks,

**Comment by dershow** [comment]
I had tried to change the port numbers in the example, instead of in the FG command line.  (ie run on 5501) and it seemed that this was causing a problem.  Do the version number correspond to port?  What is meant by version for the code?

I can now get simple_gui.py to run.  
But, I'm still getting an error with simple_ctrls.py

**Comment by julianneswinoga** [comment]
Thanks for the bug report :smile: 
Can I ask what command you're running FlightGear with? For the `simple_gui.py` example it should be something like `fgfs --native-gui=socket,out,30,localhost,5504,udp`.

The name of the connection (`native-gui`) tells FlightGear to output GUI data (in the form of [net_gui.hxx](https://github.com/FlightGear/flightgear/blob/next/src/Network/net_gui.hxx)) on port `5504`. The python script will then connect to that port to receive that data with `gui_conn.connect_rx('localhost', 5504, gui_callback)`.

The version parameter changes how the data is interpreted. Different FlightGear versions can change how/what data is output on those interfaces. Right now only the FDM interface has two different versions (24 and 25). Ctrls and GUI interfaces only have one version (27 and 8 respectively).
A future improvement would be to auto-detect these versions and change how the data is parsed but I haven't gotten around to that yet :sweat_smile:

**Comment by dershow** [comment]
Sure.  
I had figured that any port would work as long as the example and FG were matched.  So, I ran flightgear with this:
`--native-fdm=socket,out,30,localhost,5501,udp --native-fdm=socket,in,30,localhost,5502,udp`
and was able to run simple_fdm.py.  
Instead of stopping and restarting FG, I thought that it would be quicker to make a quick change to my local copy of simple_gui.py from this:
`gui_event_pipe = gui_conn.connect_rx('localhost', 5504, gui_callback)`
to this:
`gui_event_pipe = gui_conn.connect_rx('localhost', 5501, gui_callback)`


I figured that I could just use the a different port (it seemed harmless enough....).  And, I tried the same thing for simple_ctrls.py.  
I was then able to get them to work by running FG with the exact variables that you had suggested.  
So, it seems that as written, simple_gui.py will work, but will not work if I just change FG and that script to use port 5501.  I hope that helps clarify what I was seeing (and might help with auto-detect?)

**Comment by julianneswinoga** [comment]
Yes the key difference is that FlightGear can output multiple streams of data at the same time! For example:
`fgfs --native-fdm=socket,out... --native-fdm=socket,in... --native-ctrls=socket,out... --native-ctrls=socket,in... --native-gui=socket,out... --native-gui=socket,in...`
would tell FlightGear to output data and receive data for each interface (out/in for FDM, out/in for Ctrls, out/in for GUI).
It's important to match up your Python script and FlightGear command so that the data can be parsed correctly :smiley: 

I'm going to close this issue as it seems this is more a documentation problem than a software bug, thanks again!
